<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    	<?php foreach($datas as $data): ?>
			<tr>
				<td>
					<img src="<?= 'application/www/images/meals/'.$data->getPhoto() ?>" alt="<?= $data->getName() ?>">
				</td>
				<td>
					<p><?= $data->getName() ?></p>
					<p><?= $data->getDescription() ?></p>
				</td>
				<td><p><?= $data->getSalePrice() ?></p></td>

			</tr>
    	<?php endforeach; ?>
        
    </tbody>
</table>

