<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <script src="https://kit.fontawesome.com/93fd608975.js"></script>

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
    <?php if(isset($_SESSION['Id'])):?>
    
        <li>
            <ul>
                <li><a href="<?= $requestUrl.'/booking/' ?>" id="buttonBooking"><button class="button button-primary">Réserver</button></a></li>
                <li><a href="<?= $requestUrl.'/order/' ?>" id="buttonOrder"><button class="button button-primary">Commander</button></a></li>
            </ul>
        </li>
        <li>
            <ul>
                <li><?= 'Bonjour' ?><a><?= $_SESSION['FirstName'] . ' ' . $_SESSION['LastName'] ?></a><?= ' !' ?></li>
                <li><a href="<?= $requestUrl.'/deconnexion/' ?>"><button class="button button-cancel" id="buttonDisconnect">Déconnexion</button></a></li>
            </ul>
        </li>

    <?php else: ?>

        <li ><a href="<?=$requestUrl.'/newaccount/'?>"><button id="buttonNewAccount" class="button button-primary">Créer un compte</button></a></li>

        <li><a href="<?=$requestUrl.'/login/'?>"><button id="buttonConnect" class="button button-primary">Connexion</button> </a></li>

    <?php endif; ?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>