


<form method="POST" class="generic-form">
	<h2><i class="fas fa-user"></i> Mise à jours d'un compte client</h2>
	<ul >
		<?php if (isset($erreur)): ?>
	<div class="error-message"><h3>Il y a 1 erreur(s) dans le formulaire !</h3><p><?= $erreur ?></p></div>
<?php endif;?>
	<li><ul>
		<fieldset>
			<legend><i class="fas fa-book"></i> Identité et coordonnées</legend>
		<li><label for="LastName">Nom: </label>
		<input name="LastName" id="LastName" type="text" value="<?= $LastName ?>"></li>
	<li><label for="FirstName">Prénom: </label>
	<input name="FirstName" id="FirstName" type="text" value="<?= $FirstName ?>"></li>
	<li>
		<label for="day">Date de naissance: </label>
			<select name="day" id="day">
				<?php for($i = 1; $i < 32; $i++): ?>
					<?php if ($date[2] == $i): ?>
						<option value="<?= $i ?>" selected="selected"><?= $i ?></option>
					<?php else: ?>
						<option value="<?= $i ?>"><?= $i ?></option>
					<?php endif; ?>
				<?php endfor; ?>
			</select>/
			<select name="month">
				<?php for($i = 0;$i < 12; $i++): ?>
					<?php if ($date[1] == $i): ?>
						<option value="<?= $i ?>" selected="selected"><?= $i ?></option>
					<?php else: ?>
						<option value="<?= $i ?>"><?= $i ?></option>
					<?php endif; ?>
				<?php endfor; ?>
			</select>/
			<select name="year">
				<?php for($i = 1940; $i < 2019; $i++): ?>
					<?php if ($date[0] == $i): ?>
						<option value="<?= $i ?>" selected="selected"><?= $i ?></option>
					<?php else: ?>
						<option value="<?= $i ?>"><?= $i ?></option>
					<?php endif; ?>
				<?php endfor; ?>
			</select>
		
	</li>
	<li><label for="Address">Adresse: </label>
	<textarea name="Address" id="Address"><?= $Address ?></textarea>
	<li><label for="City">Ville: </label>
	<input name="City" id="City" type="text" value="<?= $City ?>"></li>
	<li><label for="ZipCode">Code Postal: </label>
	<input name="ZipCode" id="ZipCode" type="text" value="<?= $ZipCode ?>"></li>
	<li><label for="Country">Pays: </label>
	<input name="Country" id="Country" type="text" value="<?= $Country ?>"></li>
	<li><label for="Phone">Téléphone: </label>
	<input name="Phone" id="Phone" type="text" value="<?= $Phone ?>"></li>
	</fieldset>
	</ul></li>
	<li>
		<ul>
	<fieldset>
		<legend><i class="fas fa-lock"></i> Inforamtions d'authentification</legend>
	<li><label for="Email">E-mail: </label>
	<input name="Email" id="Email" type="text" value="<?= $Email ?>"></li>
	<li><label for="Password">Mot de passe: </label>
	<input name="Password" id="Password" type="password" value="<?= $password ?>"></li>
	</fieldset></ul></li>
	<button class="button button-primary" id="buttonEditSubmit">Mettre à jour</button>
	<button class="button button-cancel" id="buttonEditCancel">Annuler</button>
	
</form>
