

	<main>
	
	<!-- slider -->

	
		<section id="description">
			<h1>Création et vente de tableaux<br>Art contemporain , figuratif ou abstrait<br> Réalisation sur demande ou solon la disponibilité des tableaux de la galerie</h1>
			
			<article>
				<h2>Photographie</h2>
				<p>Impression ou envoi de fichier numérique sur demande</p>
			</article>

		</section>
		<section id="event">
			
			<ul>
				<li>
			<article>
				<h3>Last news</h3>
				<p>lorem ipsum dolor</p>
				<img src="img/img.jpg" alt="new_1"/>
			</article>
		</li>
		<li>
			<article>
				<h3>Last news</h3>
				<p>lorem ipsum dolor</p>
					<img src="img/img.jpg" alt="new_2"/>
			</article>
			</li>
		</ul>
		</section>
		
	</ul>
		
	</main>
