



	<main>
	
	<form method="POST">
	<table id="loginTable">
		<tbody>
			<tr>
				<td><label for="email">email</label></td>
				<td><input name="email" id="email" type="text"></td>
			</tr>
			<tr>
				<td><label for="password">password</label></td>
				<td><input name="password" id="password" type="password"></td>
			</tr>
			<tr>
				<td><input id="loginOk" type="submit" value="Se connecter"></td>
				<td><input id="loginCancel" type="submit" value="Annuler"></td>
			</tr>
		</tbody>
	</table>
	</form>
	

		
	</main>
