<main>
	<?php if(isset($erreur)): ?>
		<h3><?= $erreur ?></h3>
	
	<?php endif; ?>
	<form method="POST">
		<table id="registerTable">
			<tr>
				<td><label for="pseudo">pseudo: </label></td>
				<td><input id="pseudo" name="pseudo" type="text"></td>
			</tr>
			<tr>
				<td><label for="prenom">prenom: </label></td>
				<td><input id="prenom" name="prenom" type="text"></td>
			</tr>
			<tr>
				<td><label for="nom">nom: </label></td>
				<td><input id="nom" name="nom" type="text"></td>
			</tr>
			<tr>
				<td><label for="email">email: </label></td>
				<td><input id="email" name="email" type="text"></td>
			</tr>
			<tr>
				<td><label for="password">password</label></td>
				<td><input id="password" name="password" type="password"></td>
			</tr>
			<tr>
				<td><input id="registerOk" type="submit" value="S'enregistrer"></td>
				<td><input id="registerCancel" type="submit" value="Annuler"></td>
			</tr>
		</table>

		

	</form>


</main>