
<form method="POST" class="generic-form">
	<h2><i class="fas fa-shopping-cart"></i> Passer une commande</h2>
	<ul >
		<?php if (isset($erreur)): ?>
		<div class="error-message">
			<h3>Il y a 1 erreur(s) dans le formulaire !</h3>
			<p><?= $erreur ?></p>
		</div>
		<?php endif;?>
		<fieldset>
			<legend>Ajouter un article</legend>
			<li>
				<label for="meal">Nom: </label>
				<select name="meal" id="meal">
				<?php foreach($meals as $meal): ?>
				<option value="<?= $meal->getId() ?>"><?= $meal->getName() ?></option>

				<?php endforeach; ?>
				</select>
			</li>
			<li id="mealInfo" class="meal-details no-left-label" data-id="<?= $meals[0]->getId() ?>" data-priceEach="<?= $meals[0]->getSalePrice() ?>">
				<img src="<?= $wwwUrl.'/images/meals/'.$meals[0]->getPhoto()  ?>" alt="<?= $meals[0]->getName() ?>">
				<p><?= $meals[0]->getDescription() ?></p>
				<p>Prix: <?= $meals[0]->getSalePrice() ?></p>
				
			</li>
			<li>
				<label for="QuantityOrdered">Quantité: </label>
				<input name="QuantityOrdered" id="QuantityOrdered" type="text" >
			</li>
			<button class="button button-primary" id="addOrder">Ajouter</button>
		</fieldset>
		<fieldset>
				<legend>Récapitulatif de la commande</legend>
				<table id="orderInfo" class="generic-table" data-orderId="<?=$order->getId()?>">
					<thead>
						<tr>
							<th>Quantité</th>
							<th>Produit</th>
							<th>Prix Unitaire</th>
							<th>Prix Total</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<?php if(isset($order) && !empty($order->getOrderLine())): ?>
						
						<?php 	$ordersline = $order->getOrderLine();
								foreach($ordersline as $orderline): ?>
						<tr>
							<td><?= $orderline->getQuantityOrdered() ?></td>
							<td><?= $orderline->getMeal()->getName() ?></td>
							<td><?= $orderline->getPriceEach() ?></td>
							<td><?= $orderline->getPriceEach() * $orderline->getQuantityOrdered() ?></td>
							<td><i data-id="<?= $orderline->getId()?>" class="fas fa-trash-alt"></i></td>	
						</tr>
						<?php endforeach; ?>
					<?php endif; ?>
					</tbody>
				</table>

		</fieldset>
		
		</ul>
</form>

		<a href="<?= $requestUrl .'/payment/'?>"><button class="button button-primary" id="buttonOrderSubmit">Valider la commande</button></a>
		<button class="button button-cancel" id="buttonOrderCancel">Annuler</button>
