<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<ul>
		<li id="html_page">
			<?php foreach($src_spec as $sr_spec):?>
			
			<?=$sr_spec."<br>"?>


			<?php endforeach; ?>
		</li>
		

		<li id="css"><?php foreach($css as $cs):?>
			
			<?=$cs."<br>"?>


			<?php endforeach; ?>
		</li>
		 <li id="html"><?php foreach($src as $sr): ?>
		 			<?= $sr?>
		 	<?php endforeach; ?>
		 </li> 
		<li id="js"></li>
	</ul>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" ></script>
	<script src="js/script.js"></script>
</body>
</html>