<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<ul>
		<li><button id="start">start</button> <button id="pause">pause</button></li>
		<li id="data"></li>
	</ul>
		
	<ul>
		<li id="html_page">
			
			
		</li>
		

		<li id="css">
			
			
		</li>
		 <li id="html">
		 </li> 
		<li id="js"></li>
	</ul>

	<script src="https://code.jquery.com/jquery-3.4.1.min.js" ></script>
	<script src="js/script.js"></script>
</body>
</html>