    <main>
      <a id="menu_1" hre="admin.php"><i class="fas fa-cogs"></i> Panneau d'administration</a>
      <a id="new_article" href="article_new.php">Rédiger un nouvel article</a>
      <button id="disconnect" >se deconnecter</button>
      <table id="admin_table">
        <caption>Liste des articles</caption>
        <thead>
            <tr>
            <th>Titre</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th></th>
            <tr>
        </thead>
        <tbody>
            <?php foreach($articles as $article): ?>
                <tr>
                    <th><a href="article.php?id=<?=$article['art_id']?>"><?=htmlspecialchars($article['art_titre'])?></a></th>
                    <?php if(strlen($article['art_contenu']) > 75)
                    $tmp = substr($article['art_contenu'], 0, 75) . " [...]";
                    else
                        $tmp = $article['art_contenu'];?>
                    <td><?=htmlspecialchars($tmp)?></td>
                    <td><?=htmlspecialchars($article['aut_prenom'])?><br><?=htmlspecialchars($article['aut_nom'])?></td>
                    <td><?=$article['cat_nom']?></td>
                    <td><a href="article_modif.php?id=<?=$article['art_id']?>"><i class="fas fa-pen"></i></a><br><a href="delete.php?id=<?=$article['art_id']?>"><i class="fas fa-times"></i></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
      </table>
    </main>
    <footer>
     
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="js/script.js"></script>
</body>
    
</html>