<!DOCTYPE html>
<html lang="fr">

<head>
    <title>TITRE DU PROJET</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="css/normalize.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
</head>

<body>
    <header>

    </header>
    <main>
    	<h1>encore un blog ?! #nonmaisallo</h1>
  		<a id="admin_link" href="admin.php">Administration</a>
      <a id="menu_1" hre="admin.php">Panneau d'administration</a>
      <a href="article_new.php">Rédiger un nouvel article</a>
      <button id="disconnect" >se deconnecter</button>
      <table>
        <thead>
            <tr>
            <th>Titre</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th></th>
            <tr>
        </thead>
        <tbody>
            <?php foreach($articles as $article): ?>
                <tr>
                    <th><a href="article.php?id=<?=$article['art_id']?>"><?=$article['art_titre']?></a></th>
                    <td><?=$article['art_contenu']?></td>
                    <td><?=$_SESSION['prenom']?><br><?=$_SESSION['nom']?></td>
                    <td><?="article type"?></td>
                    <td><a href="article_modif.php?id=<?=$article['art_id']?>">mod</a><br><a href="delete.php?id=<?=$article['art_id']?>">del</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
      </table>
    </main>
    <footer>
     
    </footer>
    <script src="js/script.js"></script>
</body>
    
</html>