
    <main>
         <a id="menu_1" href="article.php"><i class="far fa-file-alt"></i> Article</a>
         <div id="art_art">
         <h2><?= $article['art_titre'] ?></h2>
                
            <?php if($article['art_img'] != ""): ?>
            <img id="art_img" src="<?=$article['art_img']?>" alt="<?=$article['art_titre']?>">
                        <?php endif; ?>
            <p id="art_p"><?= $article['art_contenu'] ?></p>

          <p>Rédigé par <?= htmlspecialchars($article['aut_prenom']) . " " . htmlspecialchars($article['aut_nom']) . " le " . $article['art_datetime']?></p>
           </div>
          <?php if (!empty($commentarys)): ?>
            <hr>
             <ul id="comment">
            <?php foreach($commentarys as $commentary): ?>
                <li><p><i class="fas fa-comment"></i> Rédigé par <?=  htmlspecialchars($commentary['com_pseudo'])?></p></li>
                 <li><p><?= $commentary['com_texte']?></p></li>
         <?php endforeach; ?>
          </ul> 
      <?php endif;?>
        <hr>
        <fieldset id="new_commentary">
            <legend><i class="far fa-comment"></i> Nouveau commentaire</legend>
           
                <form action="article.php?id=<?= $_GET['id'] ?>" method="post">
                  <ul>
                <li><label for="pseudo">pseudo: </label></li><li><input id="pseudo" name="pseudo" type="text" size="60"></li>
                <li><label for="commentary">Commentaire: </label></li><li><textarea id="commentary" name="commentary" cols="59" rows="7"></textarea></li>
                
           <li ><input id="ok_com"  type="submit" value="Ajouter">
            <input id="cancel_com" type="submit" value="Annuler"></li>
            <ul>
        
    </form>
    </fieldset>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
     <script src="trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="js/script.js"></script>
    <script src="js/form.js"></script>
    <footer>
     
    </footer>
</body>

</html>