        <main>
        <a id="menu_1" href="article_modif.php?id=<ph= $_GET['id'] ?>"> <i class="fas fa-pen"></i> Editer article</a>

    <form method="post" action="article_modif.php?id=<?= $_GET['id'] ?>">
      <fieldset id="art_modif">
            <legend><i class="far fa-sticky-note"></i> Article</legend>
            <ul>
                <li><label for="title">Titre: </label></li>
                <li><input id="title" type="text" name="title" size="60" value="<?= $article['art_titre'] ?>"></li>
                <li><label for="article">Article: </label></li>
                <li><textarea id="content" cols="59" rows="7" name="content"><?= $article['art_contenu'] ?></textarea></li>
                <li><input id="ok_mod" type="submit" value="Mettre à jour">
                    <input id="cancel_mod" type="submit" value="Annuler">
                </li>
                
            </ul>
        </fieldset>
        </form>

        <table id="comm">
            <thead><tr><th>pseudo</th><th>commentaire</th><th>date commentaire</th><th></th></tr></thead>
            <tbody>
                <?php foreach($commentaires as $commentaire): ?>

                    <form method="post" action="modif_com.php?id=<?=$commentaire['com_id']?>">
                    <tr>
                        <td><input name="com_pseudo" value="<?= strip_tags($commentaire['com_pseudo']) ?>"></td>
                        <td><textarea cols="50" rows="5" type="text" name="com_content" ><?= htmlspecialchars($commentaire['com_texte']) ?></textarea></td>
                        <td><?= $commentaire['com_datetime'] ?></td>
                        <td><button class="modif_com"><i class="fas fa-pen"></i></button><br><button class="delete_com" data-id="<?=$commentaire['com_id']?>"><i class="fas fa-times"></i></button></td>

                    </tr>
                    </form>
                <?php endforeach; ?>
            </tbody>
        </table>
    </main>
    <footer>
     
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="trumbowyg/dist/trumbowyg.min.js"></script>
    <script src="js/script.js"></script>
    <script src="js/form.js"></script>
</body>

</html>