<!DOCTYPE html>
<html lang="fr">

<head>
    <title>TITRE DU PROJET</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/93fd608975.js"></script>
    <link rel="stylesheet" href="trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
</head>

<body>
    <header>
		<h1><a id="header_title" href="index.php"><i class="fas fa-microphone"></i> encore un blog ?! #nonmaisallo</a></h1>
		<ul>
		<li id="admin"><i class="fas fa-cogs"></i> Administration
		<table id="admin_hide">
            <tbody>
			<form action="admin.php" method="post">
			 <tr><th><label for="user" >user: </label></th>
        <td><input type="text" name="user" id="user"></li></td></tr>
         <tr><th><label for="password" >password: </label></th>
        <td><input type="password" name="password" id="password"></li></td></tr>
        <tr><th><input type="submit" value="s'identifier"></th>
        </form>
        <form action="register.php">
			<td><input type="submit" id="register" value="s'enregistrer"><td>
			</form>
        </tr>
        </tbody>
    </table>
        </li>


		</ul>
	</li>
</ul>
    </header>