
    <main>
    	
      	<a id="menu_1" hre="index.php"><i class="fas fa-home"></i> Acceuil</a>
		
		<?php foreach ($articles as $article):?>
			<article id="art_index">
							<h3><a id="art_title" href="article.php?id=<?=$article['art_id']?>"><i class="far fa-hand-point-right"></i> <?=htmlspecialchars($article['art_titre'])?></a></h3>	
				<?php if(strlen($article['art_contenu']) > 75)
					$tmp = substr($article['art_contenu'], 0, 75) . " [...]";
					else
						$tmp = $article['art_contenu'];?>
				<p><?=htmlspecialchars($tmp)?></p>
				<p>Rédigé par <?= htmlspecialchars($article['aut_prenom']) . " " . htmlspecialchars($article['aut_nom']) . " le " . $article['art_datetime'] ?></p>
			</article>
		<?php endforeach; ?>
    </main>
    <footer>
     
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    	<script src="js/script.js"></script>
</body>


</html>