    <main>
        <a id="menu_1" href="register.php"><i class="fas fa-pen"></i> S'enregistrer</a>
      <form action="register.php" method="post">
        <table>
        <tr><th>
        <label for="user" >user: </label></th>
        <td><input type="text" name="user" id="user"></td></tr>
        <tr><th><label for="nom">nom: </label></th>
        <td><input type="text" name="nom" id="nom"></td></tr>
        <tr><th><label for="prenom">prenom: </label></th>
        <td><input type="text" name="prenom" id="prenom"></td></tr>
        <tr><th><label for="email">email: </label></th>
        <td><input type="text" name="email" id="email"></td></tr>
        <tr><th><label for="password" >password: </label></th>
        <td><input type="password" name="password" id="user"></td></tr>
        <tr><th></th><td><input type="submit" value="s'enregistrer"></td></tr>
       </table>
        

      </form>
    </main>
    <footer>
     
    </footer>
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" ></script>
    <script type="text/javascript" src="js/form.js"></script>
</body>

</html>